filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /home/deng/environment/filebeat/log/test_mapping.log
    fields:
      index_tag: 'inspect01'
    scan_frequency: 10s
    # 单条日志最大10MB,超过被截断, 与queue.mem.event 相乘即为filebeat可能占用的最大内存
    max_bytes: 10485760
    # 每次打开文件的buffer大小, 设置过小会导致多次读取文件,默认16K
    harvester_buffer_size: 16384

  - type: log
    id: test-filebeat-02
    enabled: true
    paths:
      - /home/deng/environment/filebeat/log/test_filebeat.log
    fields:
      index_tag: 'inspect02'
    scan_frequency: 10s
    max_bytes: 10485760
    harvester_buffer_size: 16384

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.ilm.enabled: false


output.elasticsearch:
  hosts: ["localhost:9200"]
  pipeline: "testFileBeat"
  # 每次发送最多 多少行数据
  bulk_max_size: 1000
  indices:
    - index: "myindex01"
      when.equals:
        fields:
          index_tag: "inspect01"
    - index: "myindex02"
      when.equals:
        fields:
          index_tag: "inspect02"
  
  pipelines:
    - pipeline: "testFileBeat01"
      when.equals:
        fields:
          index_tag: "inspect01"    
    - pipeline: "testFileBeat01"
      when.equals:
        fields: 
          index_tag: "inspect02"

  username: "elastic"
  #password: "${ES_PWD}"
  password: "123456"

queue.mem:
  # 内存队列可保存的日志数量 默认4096 可以设置为2048 避免OOM
  events: 4096
  # 触发刷写的最小日志数量 默认2048 建议512
  flush.min_events: 2048
  # 触发刷写的时间间隔 默认1s 建议5-10s
  flush.timeout: 1s


